### PR TITLE
Issue #7: Added unit tests

### LINKED ISSUE #7: add some tests
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | x.y.z

### PR DESCRIPTION
**Pull request by SergiuBota1**

### CODE REVIEW

File: src/Totp.php [hunk 1]
```diff
@@ -22,7 +45,7 @@ public function __construct(
      */
     public function generateSecretBase32(int $length = 16): string
     {
-        $chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
+        $chars  = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
```
Comment (alexmerlin) [inline src/Totp.php]: Since you are using it in multiple places, you should convert this into:
```php
public const string CHARACTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
```
and use it across the file/package..

**Review by alexmerlin — CHANGES_REQUESTED** [review]

**Review by alexmerlin — APPROVED** [review]
